[project]
name = "rzp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "einops>=0.8.0",
    "ipykernel>=6.29.5",
    "librosa>=0.10.2.post1",
    "nnaudio>=0.3.3",
    "pydub>=0.25.1",
    "timm>=1.0.12",
]
